import 'package:flutter_bloc/flutter_bloc.dart';
import '../repository/gear_repository.dart';
import '../models/gear_model.dart';
import 'add_gear_event.dart';
import 'add_gear_state.dart';

/// Manages the state for adding new gear items to the inventory.
/// 
/// Key responsibilities:
/// 1. Form state management (inputs, validation).
/// 2. "Smart" auto-filling: Maps search results (from Google Custom Search) 
///    directly into form fields to improve UX.
/// 3. Persistence: Communicates with [GearRepository] to save data.
class AddGearBloc extends Bloc<AddGearEvent, AddGearState> {
  final GearRepository _gearRepository;

  AddGearBloc({required GearRepository gearRepository})
      : _gearRepository = gearRepository,
        super(const AddGearState()) {
    
    // Field Input Handlers
    on<AddGearBrandChanged>((event, emit) => emit(state.copyWith(brand: event.brand)));
    on<AddGearModelChanged>((event, emit) => emit(state.copyWith(model: event.model)));
    on<AddGearCategoryChanged>((event, emit) => emit(state.copyWith(category: event.category)));
    on<AddGearPurchaseDateChanged>((event, emit) => emit(state.copyWith(purchaseDate: event.date)));
    on<AddGearServiceDateChanged>((event, emit) => emit(state.copyWith(lastServiceDate: event.date)));
    on<AddGearIntervalChanged>((event, emit) => emit(state.copyWith(serviceIntervalMonths: event.months)));

    // Auto-fill Handler (Integration with Search Service)
    on<AddGearAutoFilled>(_onAutoFilled);
    
    // Submission Handler
    on<AddGearSubmitted>(_onSubmitted);
  }

  void _onAutoFilled(AddGearAutoFilled event, Emitter<AddGearState> emit) {
    // Maps the external search result to our internal model state.
    // This allows the user to click a result and have the form populated automatically.
    emit(state.copyWith(
      model: event.result.title, 
      imageUrl: event.result.imageUrl ?? '', 
      // Note: Brand extraction from title could be improved with Regex in the future.
    ));
  }

  Future<void> _onSubmitted(AddGearSubmitted event, Emitter<AddGearState> emit) async {
    // Basic Validation
    if (state.brand.isEmpty || state.model.isEmpty) {
      return;
    }
    
    emit(state.copyWith(status: GearFormStatus.submissionInProgress));

    try {
      final newGear = GearItem(
        id: '', // Generated by Firestore
        userId: '', // Injected by Repository based on Auth State
        brand: state.brand,
        model: state.model,
        category: state.category,
        purchaseDate: state.purchaseDate,
        lastServiceDate: state.lastServiceDate,
        serviceIntervalMonths: state.serviceIntervalMonths,
        imageUrl: state.imageUrl,
      );

      await _gearRepository.addGear(newGear);
      emit(state.copyWith(status: GearFormStatus.submissionSuccess));
    } catch (e) {
      emit(state.copyWith(
        status: GearFormStatus.submissionFailure,
        errorMessage: e.toString(),
      ));
    }
  }
}