// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCrMb6wOcQFvaXwNn0pqjzwUDvVvkbWUQw',
    appId: '1:7698177029:web:ce0720e05903e7c755d06c',
    messagingSenderId: '7698177029',
    projectId: 'aqualog-1adf4',
    authDomain: 'aqualog-1adf4.firebaseapp.com',
    storageBucket: 'aqualog-1adf4.firebasestorage.app',
    measurementId: 'G-ZM3RNV19PP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDRpnyTpoZS6f6aKTuS13EDCjp5lSxUOn0',
    appId: '1:7698177029:android:af6af340ad9b0f7755d06c',
    messagingSenderId: '7698177029',
    projectId: 'aqualog-1adf4',
    storageBucket: 'aqualog-1adf4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB7xLYnUU9UsBbmKh0N2gXONtjDHoiWNfA',
    appId: '1:7698177029:ios:5cd52804f84107ef55d06c',
    messagingSenderId: '7698177029',
    projectId: 'aqualog-1adf4',
    storageBucket: 'aqualog-1adf4.firebasestorage.app',
    iosBundleId: 'com.example.aqualog',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB7xLYnUU9UsBbmKh0N2gXONtjDHoiWNfA',
    appId: '1:7698177029:ios:5cd52804f84107ef55d06c',
    messagingSenderId: '7698177029',
    projectId: 'aqualog-1adf4',
    storageBucket: 'aqualog-1adf4.firebasestorage.app',
    iosBundleId: 'com.example.aqualog',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCrMb6wOcQFvaXwNn0pqjzwUDvVvkbWUQw',
    appId: '1:7698177029:web:884b79fc0b3a407355d06c',
    messagingSenderId: '7698177029',
    projectId: 'aqualog-1adf4',
    authDomain: 'aqualog-1adf4.firebaseapp.com',
    storageBucket: 'aqualog-1adf4.firebasestorage.app',
    measurementId: 'G-JD6YLERJS5',
  );

}